language: node_js
node_js:
  - '10'
branches:
  only:
    - master
services:
- docker
env:
- IMAGE_NAME=codenation/code-nation-platform
install:
- docker build -t $IMAGE_NAME .
script: docker run --rm -e CI=true $IMAGE_NAME yarn test
before_deploy:
  - docker run --rm -v "$(pwd)/build:/app/build" $IMAGE_NAME yarn build
  - npm install -g firebase-tools
deploy:
  on:
    branch: master
    repo: ScriptEdcurriculum/code-nation-platform
  script: firebase deploy --force --project code-nation-platform-prod --public ./build
  skip_cleanup: true
  provider: script
