language: node
branches:
  only:
    - master
services:
  - docker
env:
  global:
    - APP_IMAGE_NAME=codenation/code-nation-platform-app
    - FUNCTIONS_IMAGE_NAME=codenation/code-nation-platform-functions
install:
  - docker build --tag $APP_IMAGE_NAME .
  - docker build --tag $FUNCTIONS_IMAGE_NAME --file functions/Dockerfile .
script:
  - docker run --rm -e CI=true $APP_IMAGE_NAME yarn test
before_deploy:
  - >-
    docker run
    --rm
    -e REACT_APP_BUGSNAG_API_KEY
    -e REACT_APP_FIREBASE_API_KEY
    -e REACT_APP_FIREBASE_PROJECT_ID
    -e REACT_APP_GOOGLE_CLIENT_ID
    -e REACT_APP_MASTER_CURRICULUM_FOLDER_ID
    -v "$(pwd)/build:/app/build"
    $APP_IMAGE_NAME
    yarn build
deploy:
  on:
    branch: master
    repo: ScriptEdcurriculum/code-nation-platform
  script: >-
    docker run
    --rm
    -e FIREBASE_TOKEN
    -e RESOURCE_DIR=functions
    -v "$(pwd)/build:/app/build"
    $FUNCTIONS_IMAGE_NAME
    yarn
    --cwd functions
    run
    firebase deploy
    --force
    --project $REACT_APP_FIREBASE_PROJECT_ID
    --public ./build
  skip_cleanup: true
  provider: script
